language: python

matrix:
  include:
    - env: PYTHON_VERSION=2
      env: DOCKER_ENV=/opt/conda
    - env: PYTHON_VERSION=3
      env: DOCKER_ENV=/opt/conda/envs/py3

sudo: true

services:
  - docker

before_install:
  - pwd
  - pushd continuous_integration
  - docker build -t libhdfs3.hdfs .
  - popd
  - docker run -d -p 8020:8020 -p 50070:50070 -v $(pwd):/hdfs3 libhdfs3.hdfs
  - export CONTAINER_ID=$(docker ps -l -q)
  - sleep 60  # Wait for namenode and datanode

install:
  - pwd
  - echo PYTHON_VERSION
  - echo DOCKER_ENV
  - docker exec -it $CONTAINER_ID $DOCKER_ENV/bin/python setup.py install

script:
  - pwd
  - docker exec -it $CONTAINER_ID $DOCKER_ENV/bin/py.test hdfs3 -s -vv
