package:
    name: hdfs3
    version: 0.0.4

source:
    path: ../..

requirements:
    build:
        - python
        - libhdfs3
    run:
        - python
        - libhdfs3

about:
  home: https://github.com/dask/hdfs3
  license: BSD 
  summary: Python wrapper for libhdfs3
