package:
    name: libhdfs3
    version: 1.0.0

source:
    git_url: https://github.com/PivotalRD/libhdfs3.git

requirements:
    build:
        - libprotobuf
        - libgsasl
        - libntlm
    run:
        - libprotobuf
        - libgsasl
        - libntlm
